### ISSUE TITLE
Items Disappear After Each Refresh

### ISSUE THREAD

**Issue by ghost** [abhi-navz/react-app#1]
add local storage for added items

**Comment by abhi-navz** [comment]
I tried saving the added items to local storage , so they persist on page refresh but it's still getting cleared on refresh. will you check the code again and tell me what's the issue.

**Comment by ghost** [comment]
I don't have an environment available right now, so I couldn't check. Also, it would be good if you provide instructions in the README on how to run this app locally.

**Comment by abhi-navz** [comment]
Updated the readme file.
